### ISSUE TITLE
Package list for building on Debian Jessie

### ISSUE THREAD

**Issue by moschlar** [rockowitz/ddcutil#10]
If you maybe want to list it in your README, here's a list of packages that I had to install to be able to build and use ddcutil in Debian Jessie:

```
build-essential
pkg-config
libglib2.0-dev
libxrandr-dev
libusb-1.0-0-dev
libudev-dev
i2c-tools
```

(This list might not be complete because this isn't a freshly installed system so other packages might have already been installed beforehand.)

**Comment by rockowitz** [comment]
Thanks for the report.

I've updated the package information on the website
(http://www.ddcutil.com/building).   I also edited README.md to
emphasize that build related information is at that page.  (The
README.md change will go out with the next release.)

Can I prevail on you to run "ddcutil Interrogate" and send me the
output?   It helps me understand the variety of systems and monitors
that are out there.

Sanford
