### ISSUE TITLE
ddcutil on laptops which use standard LVDS/EDP brightness interface

### ISSUE THREAD

**Issue by xCuri0** [rockowitz/ddcutil#103]
Some older laptops used custom methods of brightness for the CCFL backlight but most new ones control brightness using the ddc i2c pins on the display. ddcutil finds this i2c interface but doesnt successfully initialize DDC on it. does it use standard interface other than ddc ? i am interested in doing this so i can set backlight brightness without display driver running.

**Comment by rockowitz** [comment]
Newer laptops use embedded display port (eDP) panels, which have an I2C 
interface.  They implement slave address x50, which allows programs to 
read the EDID in the expected way.  However, they do not implement slave 
address x37, i.e. they do not support DDC/CI.

If eDP panels did implement DDC/CI, ddcutil  would support it. For each 
I2C bus that could possibly be associated with a monitor, as part of 
display detection ddcutil attempts to read the EDID at slave address 
x50.  If successful, it then attempts to communicate on slave address 
x37.  If that fails, and display detection is occurring in the context 
of "ddcutil detect --verbose", ddcutil then looks for a possible reason, 
and checks to see if the display is a laptop.  If so, it then reports 
that laptops to not support DDC/CI.

Sanford
