### ISSUE TITLE
Can the HDCP support be determined?

### ISSUE THREAD

**Issue by linuxhw** [rockowitz/ddcutil#107]
Haven't found anything about HDCP support in the current output of `ddcutil-0.9.9-dev probe`.

Is this info can be accessed?

**Comment by rockowitz** [comment]
HDCP and DDC are carried over the same wires in HDMI, which can lead to 
stability issues (see 
https://luxielectronics.com/attachments/File/HDCP_and_EDID_Demystified.pdf). 
At the protocol level there's no interaction - DDC can neither control 
nor detect HDCP.   So HDCP is outside the scope of ddcutil.
