### ISSUE TITLE
Exit immediately if sleep-multiplier is incorrectly selected

### ISSUE THREAD

**Issue by linuxhw** [rockowitz/ddcutil#108]
Is it possible to implement an option to exit on first `Maximum retries exceeded` message due to incorrectly defined sleep-multiplier (with an error code)? People probably don't want to wait for the program to finish because the output is known to be incomplete.

Thanks.

**Comment by rockowitz** [comment]
Use the --maxtries option.  See "ddcutil --help" and for fuller 
documentation see https://www.ddcutil.com/tuning/
