### ISSUE TITLE
missing word in configuration suggestion

### ISSUE THREAD

**Issue by mdeff** [rockowitz/ddcutil#112]
```
Configuration suggestions:
   Issue:
      Group i2c does exist.
   Suggestion:
      Create group i2c. To create group i2c, use command:
         sudo groupadd --system i2c
      Assign /dev/i2c-N devices to group i2c by adding a rule to /etc/udev/rules.d
      Add the current user to group i2c:
         sudo usermod -G i2c -a <username>
      After this, you will have to logout and login again.
      The changes to the user's group list are not read until a new login.
```

```Group i2c does exist.``` should be ```Group i2c does not exist.```

Thanks for your great work on this tool!

**Comment by rockowitz** [comment]
Thanks for pointing out the message error.  I don't know what to make of 
the fact that it's been in the code for years.  The fix will be uploaded 
to branch 0.9.9-dev in a few days, along with a raft of other changes. .

Regards,
Sanford
