### ISSUE TITLE
Better error handling if i2c_dev module isn't loaded

### ISSUE THREAD

**Issue by shaicoleman** [rockowitz/ddcutil#150]
When running `ddcutil detect` or `ddcutil detect --verbose` it just returns "No displays found", without any warning or any indication what the issue is.

Adding a message such as: "Warning: the i2c_dev kernel module is not loaded" (especially if running with --verbose) or changing the message to something like "No displays found. For troubleshooting run: ddcutil environment" would help.

(ddcutil 0.9.8 on Ubuntu 20.04)

**Comment by rockowitz** [comment]
Thank you for the suggestion.  A message suggesting use of "ddcutil 
environment" is issued unless the output level is --terse.  The change 
is now present in github branch 1.0.0-dev.

**Comment by shaicoleman** [comment]
Thanks
