### ISSUE TITLE
Regression: 1.0.1 can't detect both of my monitors

### ISSUE THREAD

**Issue by carlocastoldi** [rockowitz/ddcutil#180]
I updated ddcutil to `1.0.1` on my Manjaro desktop and now ddcutil cannot detect my two monitors.

`uname -a`: `Linux carlo-manjaro 5.10.13-2-MANJARO #1 SMP PREEMPT Sat Feb 6 10:28:21 UTC 2021 x86_64 GNU/Linux` (changing to LTS 5.4.19 didn't work either)

<details align="center">
  <summary><code>ddcutil detect</code> in <code>0.9.9</code></summary>
  <pre><code>
Display 1
   I2C bus:             /dev/i2c-1
   EDID synopsis:
      Mfg id:           SAM
      Model:            LC24RG50
      Serial number:    H4ZM801857
      Manufacture year: 2019
      EDID version:     1.3
   VCP version:         2.1
Display 2
   I2C bus:             /dev/i2c-3
   EDID synopsis:
      Mfg id:           SAM
      Model:            S24B150
      Serial number:    H4MD301250
      Manufacture year: 2013
      EDID version:     1.3
   VCP version:         2.0
  </code></pre>
</details>

<details align="center">
  <summary><code>ddcutil detect</code> in <code>1.0.1</code></summary>
  <pre><code>
No displays found.
Is DDC/CI enabled in the monitor's on screen display?
Run "ddcutil environment" to check for system configuration problems.
  </code></pre>
</details>

<details align="center">
  <summary><code>ddcutil environment</code> in <code>0.9.9</code></summary>
  <pre><code>
The following tests probe the runtime environment using multiple overlapping methods.

*** Basic System Information ***

ddcutil version: 0.9.9

/proc/version:
   Linux version 5.10.13-2-MANJARO (builduser@development) (gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.36) #1 SMP PREEMPT Sat Feb 6 10:28:21 UTC 2021

Architecture:     x86_64
Distributor id:   ManjaroLinux
Release:          20.2.1
Found a known architecture

/proc/cmdline:
   BOOT_IMAGE=/boot/vmlinuz-5.10-x86_64 root=UUID=5af0480f-7819-407a-97ab-a895cdf30141 rw udev.log_priority=3 bootsplash.bootfile=bootsplash-themes/manjaro-man/bootsplash

*** Primary Check 1: Identify video card and driver ***

Obtaining card and driver information from /sys...
Primary video controller at PCI address 0000:01:00.0 (boot_vga flag is set)
   Device class:        x030000    VGA compatible controller
   Vendor:              x1002      Advanced Micro Devices, Inc. [AMD/ATI]
   Device:              x6939      Tonga PRO [Radeon R9 285/380]
   Subvendor/Subdevice: 1682/9380  XFX Pine Group Inc.
   Driver name:         amdgpu
   Driver version:      Unable to determine
   I2C device:          i2c-3      name: AMDGPU DM i2c hw bus 3
   I2C device:          i2c-1      name: AMDGPU DM i2c hw bus 1
   I2C device:          i2c-2      name: AMDGPU DM i2c hw bus 2
   I2C device:          i2c-0      name: AMDGPU DM i2c hw bus 0
Secondary video controller at PCI address 0000:00:02.0 (boot_vga flag is not set)
   Device class:        x038000    Display controller
   Vendor:              x8086      Intel Corporation
   Device:              x1912      HD Graphics 530
   Subvendor/Subdevice: 1849/1912  ASRock Incorporation
   Driver name:         i915
   Driver version:      Unable to determine
   I2C device:          i2c-8      name: i915 gmbus dpd
   I2C device:          i2c-6      name: i915 gmbus dpc
   I2C device:          i2c-7      name: i915 gmbus dpb

*** Primary Check 2: Check that /dev/i2c-* exist and writable ***

Current user: carlo (1000)

Checking /dev/i2c-* devices...

Unless the system is using the AMD proprietary driver fglrx, devices /dev/i2c-*
must exist and the logged on user must have read/write permission for those
devices (or at least those devices associated with monitors).

Typically, this access is enabled by:
  - setting the group for /dev/i2c-* to i2c
  - setting group RW permissions for /dev/i2c-*
  - making the current user a member of group i2c

Alternatively, this can be enabled by just giving everyone RW permission
The following tests probe for these conditions.

Checking for /dev/i2c-* devices...
   crw-rw-rw- 1 root root 89,  0  9 feb 14.51 /dev/i2c-0
   crw-rw-rw- 1 root root 89,  1  9 feb 14.51 /dev/i2c-1
   crw-rw-rw- 1 root root 89, 10  9 feb 14.51 /dev/i2c-10
   crw-rw-rw- 1 root root 89,  2  9 feb 14.51 /dev/i2c-2
   crw-rw-rw- 1 root root 89,  3  9 feb 14.51 /dev/i2c-3
   crw-rw-rw- 1 root root 89,  4  9 feb 14.51 /dev/i2c-4
   crw-rw-rw- 1 root root 89,  5  9 feb 14.51 /dev/i2c-5
   crw-rw-rw- 1 root root 89,  6  9 feb 14.51 /dev/i2c-6
   crw-rw-rw- 1 root root 89,  7  9 feb 14.51 /dev/i2c-7
   crw-rw-rw- 1 root root 89,  8  9 feb 14.51 /dev/i2c-8
   crw-rw-rw- 1 root root 89,  9  9 feb 14.51 /dev/i2c-9

Current user (carlo) has RW access to all /dev/i2c-* devices.

*** Primary Check 3: Check that module i2c_dev is loaded ***

Checking for module i2c_dev...
   Module i2c-dev is NOT built into kernel
   Loadable i2c-dev module found
   Module i2c_dev is loaded

*** Primary Check 4: Driver specific checks ***

Performing driver specific checks...
No driver specific checks apply.

*** Additional probes ***

Scanning /proc/modules for driver environment...
   Found video driver module:      i915
   Found other loaded module:      i2c_i801
   Found other loaded module:      i2c_smbus
   Loaded video module depends on: i915,
   Found other loaded module:      i2c_dev
   Found other loaded module:      videodev
   Found video driver module:      amdgpu
   Found other loaded module:      i2c_algo_bit
   Found other loaded module:      drm_kms_helper
   Loaded drm module depends on:   i915,amdgpu,gpu_sched,ttm,drm_kms_helper,

Testing if modules are loaded using /sys...
   Module amdgpu           is loaded
   Module fbdev            is NOT loaded
   Module fglrx            is NOT loaded
   Module fturbo           is NOT loaded
   Module i915             is loaded
   Module mgag200          is NOT loaded
   Module nvidia           is NOT loaded
   Module nouveau          is NOT loaded
   Module radeon           is NOT loaded
   Module vboxvideo        is NOT loaded
   Module vc4              is NOT loaded
   Module drm              is loaded
   Module i2c_algo_bit     is loaded
   Module i2c_dev          is loaded
   Module i2c_piix4        is NOT loaded
   Module ddcci            is NOT loaded

Examining /sys/bus/i2c/devices...
   /sys/bus/i2c/devices/i2c-3/name:   AMDGPU DM i2c hw bus 3
   /sys/bus/i2c/devices/i2c-10/name:  AUX A/port E
   /sys/bus/i2c/devices/5-0036/name:  dummy
(each_i2c_device               ) Unexpected /sys/bus/i2c/devices file name: 5-0036
   /sys/bus/i2c/devices/i2c-1/name:   AMDGPU DM i2c hw bus 1
   /sys/bus/i2c/devices/5-0052/name:  ee1004
(each_i2c_device               ) Unexpected /sys/bus/i2c/devices file name: 5-0052
   /sys/bus/i2c/devices/i2c-8/name:   i915 gmbus dpd
   /sys/bus/i2c/devices/5-0050/name:  ee1004
(each_i2c_device               ) Unexpected /sys/bus/i2c/devices file name: 5-0050
   /sys/bus/i2c/devices/i2c-6/name:   i915 gmbus dpc
   /sys/bus/i2c/devices/i2c-4/name:   AMDGPU DM aux hw bus 0
   /sys/bus/i2c/devices/5-0037/name:  dummy
(each_i2c_device               ) Unexpected /sys/bus/i2c/devices file name: 5-0037
   /sys/bus/i2c/devices/i2c-2/name:   AMDGPU DM i2c hw bus 2
   /sys/bus/i2c/devices/i2c-0/name:   AMDGPU DM i2c hw bus 0
   /sys/bus/i2c/devices/i2c-9/name:   AUX B/port B
   /sys/bus/i2c/devices/i2c-7/name:   i915 gmbus dpb
   /sys/bus/i2c/devices/i2c-5/name:   SMBus I801 adapter at f040

Env_Accumulator:
   architecture:                  x86_64
   distributor_id                 ManjaroLinux
   Drivers detected:              i915, amdgpu
   /dev/i2c device numbers:       0 1 2 3 4 5 6 7 8 9 10
   sysfs_i2c_devices_exist:       true
   /sys/bus/i2c device numbers:   0 1 2 3 4 5 6 7 8 9 10
   dev_i2c_devices_required:      true
   module_i2c_dev_needed:         true
   module_i2c_dev_builtin:        false
   loadable_i2c_dev_exists:       true
   i2c_dev_loaded_or_builtin:     true
   group_i2c_checked:             true
   group_i2c_exists:              false
   dev_i2c_common_group_name:     root
   all_dev_i2c_has_group_i2c:     false
   any_dev_i2c_has_group_i2c:     false
   all_dev_i2c_is_group_rw:       true
   any_dev_i2c_is_group_rw:       false
   cur_uname:                     carlo
   cur_uid:                       1000
   cur_user_in_group_i2c:         false
   cur_user_any_devi2c_rw:        true
   cur_user_all_devi2c_rw:        true

Configuration suggestions:
   Current user has RW access to all /dev/i2c-N devices.
   Skipping further group and permission checks.
  </code></pre>
</details>

<details align="center">
  <summary><code>ddcutil environment</code> in <code>1.0.1</code></summary>
  <pre><code>
The following tests probe the runtime environment using multiple overlapping methods.

*** Basic System Information ***

ddcutil version: 1.0.0

/proc/version:
   Linux version 5.10.13-2-MANJARO (builduser@development) (gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.36) #1 SMP PREEMPT Sat Feb 6 10:28:21 UTC 2021

Architecture:     x86_64
Distributor id:   ManjaroLinux
Release:          20.2.1
Found a known architecture

/proc/cmdline:
   BOOT_IMAGE=/boot/vmlinuz-5.10-x86_64 root=UUID=5af0480f-7819-407a-97ab-a895cdf30141 rw udev.log_priority=3 bootsplash.bootfile=bootsplash-themes/manjaro-man/bootsplash

*** Primary Check 1: Identify video card and driver ***

Obtaining card and driver information from /sys...
Primary video controller at PCI address 0000:01:00.0 (boot_vga flag is set)
   Device class:        x030000    VGA compatible controller
   Vendor:              x1002      Advanced Micro Devices, Inc. [AMD/ATI]
   Device:              x6939      Tonga PRO [Radeon R9 285/380]
   Subvendor/Subdevice: 1682/9380  XFX Pine Group Inc.
   Driver name:         amdgpu
   Driver version:      Unable to determine
   I2C device:          i2c-3      name: AMDGPU DM i2c hw bus 3
   I2C device:          i2c-1      name: AMDGPU DM i2c hw bus 1
   I2C device:          i2c-2      name: AMDGPU DM i2c hw bus 2
   I2C device:          i2c-0      name: AMDGPU DM i2c hw bus 0
Secondary video controller at PCI address 0000:00:02.0 (boot_vga flag is not set)
   Device class:        x038000    Display controller
   Vendor:              x8086      Intel Corporation
   Device:              x1912      HD Graphics 530
   Subvendor/Subdevice: 1849/1912  ASRock Incorporation
   Driver name:         i915
   Driver version:      Unable to determine
   I2C device:          i2c-8      name: i915 gmbus dpd
   I2C device:          i2c-6      name: i915 gmbus dpc
   I2C device:          i2c-7      name: i915 gmbus dpb

*** Primary Check 2: Check that /dev/i2c-* exist and writable ***

Current user: carlo (1000)

Checking /dev/i2c-* devices...

Devices /dev/i2c-* must exist and the logged on user must have read/write permission for those devices (or at least those devices associated 
with monitors).

Typically, this access is enabled by:
  - setting the group for /dev/i2c-* to i2c
  - setting group RW permissions for /dev/i2c-*
  - making the current user a member of group i2c

Alternatively, this can be enabled by just giving everyone RW permission
The following tests probe for these conditions.

Checking for /dev/i2c-* devices...
   crw-rw-rw- 1 root root 89,  0  9 feb 14.51 /dev/i2c-0
   crw-rw-rw- 1 root root 89,  1  9 feb 14.51 /dev/i2c-1
   crw-rw-rw- 1 root root 89, 10  9 feb 14.51 /dev/i2c-10
   crw-rw-rw- 1 root root 89,  2  9 feb 14.51 /dev/i2c-2
   crw-rw-rw- 1 root root 89,  3  9 feb 14.51 /dev/i2c-3
   crw-rw-rw- 1 root root 89,  4  9 feb 14.51 /dev/i2c-4
   crw-rw-rw- 1 root root 89,  5  9 feb 14.51 /dev/i2c-5
   crw-rw-rw- 1 root root 89,  6  9 feb 14.51 /dev/i2c-6
   crw-rw-rw- 1 root root 89,  7  9 feb 14.51 /dev/i2c-7
   crw-rw-rw- 1 root root 89,  8  9 feb 14.51 /dev/i2c-8
   crw-rw-rw- 1 root root 89,  9  9 feb 14.51 /dev/i2c-9

Current user (carlo) has RW access to all /dev/i2c-* devices.

*** Primary Check 3: Check that module i2c_dev is loaded ***

Checking for module i2c_dev...
   Module i2c-dev is NOT built into kernel
   Loadable i2c-dev module found
   Module i2c_dev is loaded

*** Primary Check 4: Driver specific checks ***

Performing driver specific checks...
No driver specific checks apply.

*** Additional probes ***

Scanning /proc/modules for driver environment...
   Found video driver module:      i915
   Found other loaded module:      i2c_i801
   Found other loaded module:      i2c_smbus
   Loaded video module depends on: i915,
   Found other loaded module:      i2c_dev
   Found other loaded module:      videodev
   Found video driver module:      amdgpu
   Found other loaded module:      i2c_algo_bit
   Found other loaded module:      drm_kms_helper
   Loaded drm module depends on:   i915,amdgpu,gpu_sched,ttm,drm_kms_helper,

Testing if modules are loaded using /sys...
   Module amdgpu           is loaded
   Module fbdev            is NOT loaded
   Module fglrx            is NOT loaded
   Module fturbo           is NOT loaded
   Module i915             is loaded
   Module mgag200          is NOT loaded
   Module nvidia           is NOT loaded
   Module nouveau          is NOT loaded
   Module radeon           is NOT loaded
   Module vboxvideo        is NOT loaded
   Module vc4              is NOT loaded
   Module drm              is loaded
   Module i2c_algo_bit     is loaded
   Module i2c_dev          is loaded
   Module i2c_piix4        is NOT loaded
   Module ddcci            is NOT loaded

Examining /sys/bus/i2c/devices...
   /sys/bus/i2c/devices/5-0036/name:  dummy
   /sys/bus/i2c/devices/5-0037/name:  dummy
   /sys/bus/i2c/devices/5-0050/name:  ee1004
   /sys/bus/i2c/devices/5-0052/name:  ee1004
   /sys/bus/i2c/devices/i2c-0/name:   AMDGPU DM i2c hw bus 0
   /sys/bus/i2c/devices/i2c-1/name:   AMDGPU DM i2c hw bus 1
   /sys/bus/i2c/devices/i2c-2/name:   AMDGPU DM i2c hw bus 2
   /sys/bus/i2c/devices/i2c-3/name:   AMDGPU DM i2c hw bus 3
   /sys/bus/i2c/devices/i2c-4/name:   AMDGPU DM aux hw bus 0
   /sys/bus/i2c/devices/i2c-5/name:   SMBus I801 adapter at f040
   /sys/bus/i2c/devices/i2c-6/name:   i915 gmbus dpc
   /sys/bus/i2c/devices/i2c-7/name:   i915 gmbus dpb
   /sys/bus/i2c/devices/i2c-8/name:   i915 gmbus dpd
   /sys/bus/i2c/devices/i2c-9/name:   AUX B/port B
   /sys/bus/i2c/devices/i2c-10/name:  AUX A/port E

Env_Accumulator:
   architecture:                  x86_64
   distributor_id                 ManjaroLinux
   Drivers detected:              i915, amdgpu
   /dev/i2c device numbers:       0 1 2 3 4 5 6 7 8 9 10
   sysfs_i2c_devices_exist:       true
   /sys/bus/i2c device numbers:   0 1 2 3 4 5 6 7 8 9 10
   dev_i2c_devices_required:      true
   module_i2c_dev_needed:         true
   module_i2c_dev_builtin:        false
   loadable_i2c_dev_exists:       true
   i2c_dev_loaded_or_builtin:     true
   group_i2c_checked:             true
   group_i2c_exists:              false
   dev_i2c_common_group_name:     root
   all_dev_i2c_has_group_i2c:     false
   any_dev_i2c_has_group_i2c:     false
   all_dev_i2c_is_group_rw:       true
   any_dev_i2c_is_group_rw:       false
   cur_uname:                     carlo
   cur_uid:                       1000
   cur_user_in_group_i2c:         false
   cur_user_any_devi2c_rw:        true
   cur_user_all_devi2c_rw:        true

Configuration suggestions:
   Current user has RW access to all /dev/i2c-N devices.
   Skipping further group and permission checks.
  </code></pre>
</details>

`diff` of the two `environment` outputs:
```diff
1d0
< 
6c5
< ddcutil version: 0.9.9
---
> ddcutil version: 1.0.0
50,52c49,50
< Unless the system is using the AMD proprietary driver fglrx, devices /dev/i2c-*
< must exist and the logged on user must have read/write permission for those
< devices (or at least those devices associated with monitors).
---
> Devices /dev/i2c-* must exist and the logged on user must have read/write permission for those devices (or at least those devices associated
> with monitors).
127,128d124
< /sys/bus/i2c/devices/i2c-3/name:   AMDGPU DM i2c hw bus 3
< /sys/bus/i2c/devices/i2c-10/name:  AUX A/port E
130,138d125
< (each_i2c_device               ) Unexpected /sys/bus/i2c/devices file name: 5-0036
< /sys/bus/i2c/devices/i2c-1/name:   AMDGPU DM i2c hw bus 1
< /sys/bus/i2c/devices/5-0052/name:  ee1004
< (each_i2c_device               ) Unexpected /sys/bus/i2c/devices file name: 5-0052
< /sys/bus/i2c/devices/i2c-8/name:   i915 gmbus dpd
< /sys/bus/i2c/devices/5-0050/name:  ee1004
< (each_i2c_device               ) Unexpected /sys/bus/i2c/devices file name: 5-0050
< /sys/bus/i2c/devices/i2c-6/name:   i915 gmbus dpc
< /sys/bus/i2c/devices/i2c-4/name:   AMDGPU DM aux hw bus 0
140,141c127,128
< (each_i2c_device               ) Unexpected /sys/bus/i2c/devices file name: 5-0037
< /sys/bus/i2c/devices/i2c-2/name:   AMDGPU DM i2c hw bus 2
---
> /sys/bus/i2c/devices/5-0050/name:  ee1004
> /sys/bus/i2c/devices/5-0052/name:  ee1004
143,144c130,133
< /sys/bus/i2c/devices/i2c-9/name:   AUX B/port B
< /sys/bus/i2c/devices/i2c-7/name:   i915 gmbus dpb
---
> /sys/bus/i2c/devices/i2c-1/name:   AMDGPU DM i2c hw bus 1
> /sys/bus/i2c/devices/i2c-2/name:   AMDGPU DM i2c hw bus 2
> /sys/bus/i2c/devices/i2c-3/name:   AMDGPU DM i2c hw bus 3
> /sys/bus/i2c/devices/i2c-4/name:   AMDGPU DM aux hw bus 0
145a135,139
> /sys/bus/i2c/devices/i2c-6/name:   i915 gmbus dpc
> /sys/bus/i2c/devices/i2c-7/name:   i915 gmbus dpb
> /sys/bus/i2c/devices/i2c-8/name:   i915 gmbus dpd
> /sys/bus/i2c/devices/i2c-9/name:   AUX B/port B
> /sys/bus/i2c/devices/i2c-10/name:  AUX A/port E

```

EDIT: oh right, I have an AMD R9 380 to which I connected my Display 1 with HDMI and Display 2 with DVI-D

**Comment by rockowitz** [comment]
On 1.0.1, please run the following commands and submit the output: 

$ ddcutil environment --very-verbose
$ ddcutil detect --verbose --trcfunc i2c_get_raw_edid_by_fd --trcfunc i2c_get_edid_bytes_directly
$ ddcutil detect --verbose --f4

(**--f4** is a "utility" option currently used to trigger test code) 

Thank you.

**Comment by carlocastoldi** [comment]
> On 1.0.1, please run the following commands and submit the output:
> 
> $ ddcutil environment --very-verbose
> $ ddcutil detect --verbose --trcfunc i2c_get_raw_edid_by_fd --trcfunc i2c_get_edid_bytes_directly
> $ ddcutil detect --verbose --f4
> 
> (**--f4** is a "utility" option currently used to trigger test code)
> 
> Thank you.

[ddcutil_detect_f4.log](https://github.com/rockowitz/ddcutil/files/5953888/ddcutil_detect_f4.log)
[ddcutil_detect.log](https://github.com/rockowitz/ddcutil/files/5953890/ddcutil_detect.log)
[ddcutil_environment.log](https://github.com/rockowitz/ddcutil/files/5953891/ddcutil_environment.log)

Thank you a lot for the quick reply!
And sorry if I kept you waiting :\

**Comment by rockowitz** [comment]
I'm surprised by the trace output, though I have hu a hunch.                                                                                   
What happens if you call detect with option ***--edid-read-size 128*** or ***--edid-read-size 256***?

**Comment by carlocastoldi** [comment]
>  What happens if you call detect with option _**--edid-read-size 128**_
```
Display 1
   I2C bus:  /dev/i2c-1
   EDID synopsis:
      Mfg id:               SAM
      Model:                LC24RG50
      Product code:         3984
      Serial number:        H4ZM801857
      Binary serial number: 1129788471 (0x43573437)
      Manufacture year:     2019
      EDID version:         1.3
   VCP version:         2.1

Display 2
   I2C bus:  /dev/i2c-3
   EDID synopsis:
      Mfg id:               SAM
      Model:                S24B150
      Product code:         2435
      Serial number:        H4MD301250
      Binary serial number: 808596788 (0x30323534)
      Manufacture year:     2013
      EDID version:         1.3
   VCP version:         2.0
```

> or _**--edid-read-size 256**_?
```
No displays found.
Is DDC/CI enabled in the monitor's on screen display?
Run "ddcutil environment" to check for system configuration problems.
```

Something positive, it seems?

**Comment by carlocastoldi** [comment]
Oh fuck me.
I am afraid I wrongly read the version my distro just published. It's `1.0.0-1` (as you can see from the first `ddcutil environment`)
I am terribly sorry, as I have actually updated to `1.0.1` the problem no longer exists :)

I hope I didn't make you waste too much time

**Comment by rockowitz** [comment]
I'm surprised by the trace output, though I have hu a hunch.                                                                                   
What happens if you call detect with option ***--edid-read-size 128*** or ***--edid-read-size 256***?
