### ISSUE TITLE
Percieved error in 45-ddcutil-i2c.rules

### ISSUE THREAD

**Issue by devonallie** [rockowitz/ddcutil#182]
The generated rule contains
`KERNEL=="i2c-[0-9]*"`
but should be
`KERNEL=="i2c-[0-9]"` (see removal of *)

The wildcard seems to confuse udev resulting none of the i2c devices being recognized.

**Comment by rockowitz** [comment]
If you have more than 9 /dev/i2c devices the asterisk is necessary.  In this context it is not a wildcard.  The string "i2c-[0-9]*" is a regular expression.  "[0-9]" matches any single character in the range 0-9, i.e. any digit. The following * indicates that the prior match can be applied any number of times, i.e. any number of digits will be matched.
