### ISSUE TITLE
ddcutil not detecting displays windows subsystem for linux

### ISSUE THREAD

**Issue by xcgt** [rockowitz/ddcutil#216]
Is this even a possibility? 

![image](https://user-images.githubusercontent.com/88842089/129216664-190e2030-6337-4c24-9af9-bf2bad905357.png)

**Comment by xcgt** [comment]
![image](https://user-images.githubusercontent.com/88842089/129216647-7c675d7d-bed3-4a60-89b7-af205b1574fa.png)

**Comment by rockowitz** [comment]
My first answer is simply no.  On reconsideration, I would qualify that to "only remotely at some future date".  

The virtualized video drivers simply don't provide access to DDC.  There are no /dev/i2c devices, no /sys or /proc entries.
