### ISSUE TITLE
./configure not finding xrandr that exists in the system

### ISSUE THREAD

**Issue by juansecaro** [rockowitz/ddcutil#230]
V 1.1, system Linux Mint 19.3, updated
![ddcutil_error](https://user-images.githubusercontent.com/5209472/140102560-5289f020-1688-439d-800f-ac967f01fd7c.png)

**Comment by rockowitz** [comment]
The error message from pkg-config is misleading.  What's missing is the xrandr development package, which on Debian based systems is libxrandr-dev.  See the [FAQ](https://www.ddcutil.com/faq#missing_package).

**Comment by juansecaro** [comment]
You are right. Sorry for not checking that out first.
