### ISSUE TITLE
Package for Ubuntu 17.04?

### ISSUE THREAD

**Issue by teknico** [rockowitz/ddcutil#24]
Thank you for the PPA on Launchpad. Any chance to build for Ubuntu versions later than 16.04, currently 17.04?

**Comment by rockowitz** [comment]
The build for 16.04 should work just fine on later Ubuntu versions.   
However, if you'd like the Open Build Service has separate builds for 
each of multiple Ubuntu versions.

Sanford

**Comment by teknico** [comment]
Sorry for being dense, but which instance of the Open Build Service should I use? I cannot find it.

**Comment by rockowitz** [comment]
See section "Installing ddcutil From Prebuilt Packages" on the 
www.ddcutil.com home page

**Comment by teknico** [comment]
Awesome, thank you!
