### ISSUE TITLE
How to prevent syslog starting and terminating events?

### ISSUE THREAD

**Issue by anktx** [rockowitz/ddcutil#246]
I use ddcutils to set monitor brightness depending of environment illumination, so it's running very often (twice a minute).
Every run I see in syslog:
```
Jan 16 12:56:39 [ddcutil] Starting.  ddcutil version 1.2.1
Jan 16 12:56:40 [ddcutil] Terminating. Returning 0
```

How to prevent this?

**Comment by rockowitz** [comment]
The Starting/Terminating messages should only be written to the system log when option --syslog is specified. This has been fixed in branch 1.2.2-dev.  Thank you for the report.
