### ISSUE TITLE
Dell DDC communication failed -- Dell P2412H/Dell P2311H

### ISSUE THREAD

**Issue by mituzora** [rockowitz/ddcutil#258]
Hi all,

I ran into an issue while testing out ddcutil with my Dell monitors.  They seem to not be able to communicate via DDC.  I know DDC/CI works, because I can set it in Windows, and with the --f6 flag, I can successfully force these monitors to accept brightness controls.  the interrogate file should be attached if you would like to take a look at it
[ddcutil.txt](https://github.com/rockowitz/ddcutil/files/8631895/ddcutil.txt)

Also, to note, sometimes it will not update the display, but if I set maxtries to 15 across the board, it seems to work.  My 3rd monitor (Huion GT-191 drawing tablet) works fine and gets detected no problem.  I have also already applied the Nvidia xorg fix, as well as added the included fix to the kernel options to be on the safe side.

**Comment by rockowitz** [comment]
It's probably the monitors.  I have a pair of Dell P2411h monitors, which I assume are very similar, and both show a lot of communication errors (as does yours, looking at the retry statistics in interrogate).  I use them for testing ddcutil's error recovery. Option **--sleep-multiplier 2.0** makes the monitor communication much more solid.

**Comment by mituzora** [comment]
Yeah, that's what I was thinking myself.  I looked at the known issues of P2411h, and thought that this sounded very similar to what my monitors are doing.  trying the **--sleep-multipler 2.0** option does help it significantly, but without the **--f6** flag ddcutil still fails to communicate.  It will work for me until I can get these monitors replaced at least, so therefore I'll go ahead and close this.  Thanks for the tip!

**Comment by rockowitz** [comment]
***--f6*** is a utility flag for experimental options. It no longer has effect n branch 1.2.3-dev.  If you are able, please build from that branch.  If communication fails,  I'll consider adding a permanent option that has the same effect as did ***--f6***.

**Comment by mituzora** [comment]
Hi, sorry for the late update.  

While on 1.2.3-dev, it does look like the **--sleep-multiplier 2.0** does seem to help the P2311H read a little bit better, it still seems to fail when actually trying to run any of the setvcp commands.  the P2412H does nothing still.  I've also tried the **--maxtries** option and still nothing.  Neither monitor responds now, so whatever the **--f6** option did, it helped at least in my case.  
[interrogate_new.txt](https://github.com/rockowitz/ddcutil/files/8697604/interrogate_new.txt)
I went ahead and attached the new interrogate file if you'd like to take a look.

**Comment by rockowitz** [comment]
As discussed, your monitors have marginal DDC implementations, compounded by the problematic I2C implementation in the Nvidia driver.  To better see what is going on, add the following options: 

***--ddc***  Report DDC communication errors
***--stats errors*** Report error and recovery statistics
***--bus N*** Specifying the I2C bus avoids probing other monitors, reducing errors 

I've reimplemented the temporary ***--f6*** option, which forces **ddcutil** to continue even if probing fails.  If it were a permanent option, it would be named something like "force-communication-success".  Does this still improve performance? If so, I expect you will still see lots of errors reported by ***--ddc*** and ***--stats errors***, they just won't be fatal.

If it is still unclear what is going on, run a failing command with option ***--trace all** and submit it.  The output will be awfully voluminous, but I'll be able to scan through it to better see where errors are happening.
