### ISSUE TITLE
Doc: range is not a number

### ISSUE THREAD

**Issue by ratijas** [rockowitz/ddcutil#285]
https://github.com/rockowitz/ddcutil/blob/f74d9ccbfdab7afbc8b8217bfe80cdc81cd2ceca/src/public/ddcutil_types.h#L45

"-3000" referenced in this doc comment is not exactly a range, it's just a number. So what's the range here? `(-INT_MIN;-3000]`, i.e. "less or equal to"?

**Comment by rockowitz** [comment]
First, there's residual complexity in **ddcutil** error number handling, left over from when the AMD proprietary video driver **fglrx** was supported using its ADL api.  The maximum Linux/BSD errno value observed is 133 (EWHPOISON). It seemed safe to assume that all errno value are in the range 1..1999.  To distinguish ADL errors from Linux errors, the ADL status codes were modulated to -2001, -2002, etc. for ADL errors, and +2001, +2002, etc.  That is, the range 2001..2999 is reserved for ADL errors.  To avoid conflict, **ddcutil** errors are numbered -3001, -3002, .. etc. Currently, the lowest **ddcutil** error number defined in file public/ddcutil_status_codes.h is -3027 (DDCRC_BAD_DATA).
