### ISSUE TITLE
changing monitor color mode

### ISSUE THREAD

**Issue by 24fpsDaVinci** [rockowitz/ddcutil#346]
on some Eizos, HP dreamcolor z27 G2 and Apple studio display there are built in reference modes (rec709, srgb, dci-p3, etc). Is this something ddcutil can change over USB? Theres support for changing reference mode under macos but i cannot find any developer documents for it. How should I probe for it? thank you

**Comment by rockowitz** [comment]
First, does the monitor use a VCP feature code to control the reference mode?  If so, it's likely feature x14 (Select Color Preset), but it could be a manufacturer reserved feature (xE0..xFF). 

If the monitor supports DDC/CI, you can use **ddcutil** to probe if the there's a feature value that changes when you change the color reference mode in the OSD.  **ddcutil getvcp scan** will check every feature value.

If a monitor's setting are controllable using USB, the question is whether it adheres to the 
[USB Monitor Control Class Specification](https://usb.org/sites/default/files/usbmon10.pdf) for communicating with the monitor's Virtual Control Panel.  **ddcutil** can communicate with it only if it adheres to the spec.  By default, USB support is disabled in **ddcutil**, option ***--enable-usb*** enables it.  To see if your monitor adheres to the spec, use **ddcutil detect --enable-usb**. 

If the monitor is controllable via USB but does not support the spec, your only option is to use the Windows app to change monitor settings and trace the packets on the USB bus. 

Finally, the manufacturer may supply a proprietary API for controlling the monitor.  For example, the  Z27x API has a set of functions for managing the color space.
