### ISSUE TITLE
With "--enable-usb=no", compile error: ‘ignored_vid_pid’ undeclared

### ISSUE THREAD

**Issue by hannob** [rockowitz/ddcutil#355]
When disabling usb (`./configure --enable-usb=no`), compilation fails with this error:

```
cmd_parser_goption.c:1607:8: error: ‘ignored_vid_pid’ undeclared (first use in this function)
```

It appears ignored_vid_pid is defined in a block with `#ifdef USE_USB`, but later used outside of the #ifdef.

I'm unfamiliar with the code, so I'm unsure if the correct fix would be to move the declaration of ignored_vid_pid out of the ifdef-block or to put the code that is accessing it inside another ifdef block.

See also: https://bugs.gentoo.org/918124

**Comment by rockowitz** [comment]
A fix for the bug you reported has been pushed to branch 2.0.2-dev with commit 4e2681a89fc5ba1ab5f909e30baf9eef0c99e5bd. Thank you for the report.
