### ISSUE TITLE
Can you put releases in the releases tab?

### ISSUE THREAD

**Issue by dracwyrm** [rockowitz/ddcutil#4]
Hi,

Currently there are no releases in the releases tab, but there are tarballs in the main repo. It would be better if the downloads were in the releases tab, which I think you can tell github to do automatically(?) and remove the tarballs from the main repository.

Thanks.

**Comment by rockowitz** [comment]
Jonathan,

Thanks for pointing this out.   Having tarballs in the main repo was a
temporary expedient which is due for replacement.   I'll look at putting
them in the releases tab. 

Sanford

**Comment by dracwyrm** [comment]
Thanks for responding. This is the github guide:
https://help.github.com/articles/creating-releases/

The part about including binaries is for anything that is not in the repo. It should create the zips and tarballs for you.

**Comment by rockowitz** [comment]
Jonathan,

Thanks for directing me to the documentation.

ddctool has just had its first formal release, 0.5.0.  github now
creates the tarball as part of the release, and it's no longer in the
mail repo.   The packaging is still a bit ragged, but progress.

Regards,
Sanford

**Comment by dracwyrm** [comment]
Sanford,

No problem. :) Keep up the great work on this tool!

Jon
