### ISSUE TITLE
Rocky Linux 9.3 display port stopped working after update

### ISSUE THREAD

**Issue by gospodinbodurov** [rockowitz/ddcutil#411]
My display port (HP EliteBook 8470p) stopped working after the latest update in Rocky Linux. Before that it was working fine. 

I tested with two different external displays and no joy. Tested the same displays with Ubuntu 22.04.4 LTS and both are working fine. Ubuntu is updated to the latest version.

Here is some debug data:

------------------------

ddcutil detect --stats errors -v
Invalid display
   I2C bus:  /dev/i2c-2
      DRM connector:                      card0-LVDS-1
      Driver:                             i915
      I2C address 0x50 (EDID) responsive: true 
      Is eDP device:                      false
      Is LVDS device:                     false
      /sys/bus/i2c/devices/i2c-2/name     i915 gmbus panel
      PCI device path:                    /sys/devices/pci0000:00/0000:00:02.0/i2c-2
   EDID synopsis:
      Mfg id:               AUO - UNK
      Model:                
      Product code:         12604  (0x313c)
      Serial number:        
      Binary serial number: 0 (0x00000000)
      Manufacture year:     2011,  Week: 0
      EDID version:         1.4
      Extra descriptor:        
      Video input definition:    0x90 - Digital Input (Digital interface not defined), Bit depth: 6
      Supported features:
         Digital display type: RGB 4:4:4
         Standard sRGB color space: False
      White x,y:        0.313, 0.329
      Red   x,y:        0.590, 0.345
      Green x,y:        0.340, 0.570
      Blue  x,y:        0.150, 0.120
      Extension blocks: 0
   EDID source: I2C
   EDID hex dump:
              +0          +4          +8          +c            0   4   8   c   
      +0000   00 ff ff ff ff ff ff 00 06 af 3c 31 00 00 00 00   ..........<1....
      +0010   00 15 01 04 90 1f 11 78 02 10 b5 97 58 57 92 26   .......x....XW.&
      +0020   1e 50 54 00 00 00 01 01 01 01 01 01 01 01 01 01   .PT.............
      +0030   01 01 01 01 01 01 ce 1d 56 e2 50 00 1e 30 26 16   ........V.P..0&.
      +0040   36 00 35 ad 10 00 00 18 df 13 56 e2 50 00 1e 30   6.5.......V.P..0
      +0050   26 16 36 00 35 ad 10 00 00 18 00 00 00 00 00 00   &.6.5...........
      +0060   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02   ................
      +0070   00 0c 4c ff 0a 3c 64 12 12 1e 65 20 20 20 00 70   ..L..<d...e   .p
   DDC communication failed
   This appears to be a laptop display. Laptop displays do not support DDC/CI.

Invalid display
   I2C bus:  /dev/i2c-5
      Driver:                             i915
      I2C address 0x50 (EDID) responsive: true 
      Is eDP device:                      false
      Is LVDS device:                     false
      /sys/bus/i2c/devices/i2c-5/name     i915 gmbus dpd
      PCI device path:                    /sys/devices/pci0000:00/0000:00:02.0/i2c-5
   EDID synopsis:
      Mfg id:               SNY - Sony
      Model:                SONY TV
      Product code:         59651  (0xe903)
      Serial number:        
      Binary serial number: 16843009 (0x01010101)
      Manufacture year:     2016,  Week: 1
      EDID version:         1.3
      Extra descriptor:        
      Video input definition:    0x80 - Digital Input
      Supported features:
         Digital display type: RGB 4:4:4 + YCrCb 4:4:4
         Standard sRGB color space: False
      White x,y:        0.283, 0.298
      Red   x,y:        0.625, 0.340
      Green x,y:        0.280, 0.595
      Blue  x,y:        0.155, 0.070
      Extension blocks: 1
   EDID source: I2C
   EDID hex dump:
              +0          +4          +8          +c            0   4   8   c   
      +0000   00 ff ff ff ff ff ff 00 4d d9 03 e9 01 01 01 01   ........M.......
      +0010   01 1a 01 03 80 a0 5a 78 0a 0d c9 a0 57 47 98 27   ......Zx....WG.'
      +0020   12 48 4c 21 08 00 81 80 a9 c0 71 4f b3 00 01 01   .HL!......qO....
      +0030   01 01 01 01 01 01 02 3a 80 18 71 38 2d 40 58 2c   .......:..q8-@X,
      +0040   45 00 40 84 63 00 00 1e 01 1d 00 72 51 d0 1e 20   E.@.c......rQ.. 
      +0050   6e 28 55 00 40 84 63 00 00 1e 00 00 00 fc 00 53   n(U.@.c........S
      +0060   4f 4e 59 20 54 56 0a 20 20 20 20 20 00 00 00 fd   ONY TV.     ....
      +0070   00 30 3e 0e 46 0f 00 0a 20 20 20 20 20 20 01 e5   .0>.F...      ..
   DDC communication failed

EXECUTION STATISTICS

DDC Related Errors:  

Count   Status Code                          Description
    2   ENXIO                        (   -6) No such device or address 
Total errors: 2

Errors Wrapped in Retry:  

Count   Status Code                          Description
    2   ENXIO                        (   -6) No such device or address 
Total errors: 2

------------------------

uname -a
Linux localhost.localdomain 5.14.0-362.24.1.el9_3.0.1.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 4 22:31:43 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

------------------------
cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.3 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.3 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.3"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"

------------------------

lspci -k | grep -EA3 'VGA|3D|Display'
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
	DeviceName: 64
	Subsystem: Hewlett-Packard Company Device 179b
	Kernel driver in use: i915

**Comment by rockowitz** [comment]
Please execute **ddcutil interrogate** and submit the output as an attachment of some sort, not inline.

**Comment by gospodinbodurov** [comment]
After latest update it started working again. 

Guess the SELinux permissions got messed up somehow. Will report if it pops up again.

Thank you!
