### ISSUE TITLE
Small suggestion for ddcutil documentation on the website

### ISSUE THREAD

**Issue by jatgh** [rockowitz/ddcutil#423]
Hello!

In the '**Special Nvidia Driver Settings**' chapter of ddcutil's documentation on the website (https://www.ddcutil.com/nvidia/) it's missing that after creating a settings file in `/etc/modprobe.d/` and before rebooting, initramfs image should also be updated (`sudo update-initramfs -u`).
For me, simple reboot didn't do and settings haven't been applied until I updated initramfs and reboot again.
Don't know if that's the case for every distro though.
Anyway I think it would be great to include that point on the page.

Thank you!

**Comment by rockowitz** [comment]
The page has been updated.  Thank you for the suggestion.
