### ISSUE TITLE
ddcui controls smaller than font size on Ubuntu 24.04

### ISSUE THREAD

**Issue by ziyuang** [rockowitz/ddcutil#441]
`ddcutil`  and `ddcui` were installed from `apt`.

![Screenshot from 2024-08-28 16-51-21](https://github.com/user-attachments/assets/300fc422-d49e-4935-9552-5625228f70b4)

Version info:

![Screenshot from 2024-08-28 16-54-20](https://github.com/user-attachments/assets/6a38c31e-6c25-462b-b234-4d5128a8e2f7)

**Comment by rockowitz** [comment]
This issue was moved to ddcui issue 61.

**Comment by rockowitz** [comment]
The versions of ddcutil and ddcui in Ubuntu 24.04 are quite old.  If you are able, please build ddcutil and ddcui from the development branches here on github, 2.1.5-dev and 0.5.4-dev respectively.
