### ISSUE TITLE
Support for Ubuntu 24.04 LTS (Noble Numbat) in Official PPA

### ISSUE THREAD

**Issue by leinardi** [rockowitz/ddcutil#459]
**Description:**

The official Launchpad PPA for ddcutil (https://launchpad.net/~rockowitz/+archive/ubuntu/ddcutil) currently supports Ubuntu releases up to 23.10 Mantic Minotaur. However, there is no package available for the latest LTS release, Ubuntu 24.04 Noble Numbat.

Ubuntu 24.04 ships with an outdated version (1.4.1) of ddcutil, and an updated PPA would allow users to access the latest features and fixes. As LTS versions are widely used and provide long-term stability, having ddcutil available through the PPA for Ubuntu 24.04 LTS would greatly benefit users who rely on the latest version of the software.

**Request:**

Please provide support for Ubuntu 24.04 LTS (Noble Numbat) in the official PPA, with an updated version of ddcutil beyond 1.4.1.

**Links:**

- [Official ddcutil Installation Documentation](https://www.ddcutil.com/install/)
- [Launchpad PPA for ddcutil](https://launchpad.net/~rockowitz/+archive/ubuntu/ddcutil)

**Comment by rockowitz** [comment]
Noble builds for ddcutil 2.1.4 and ddcui 0.5.4 have been added.

Thank you for pointing this out.
