### ISSUE TITLE
on some monitors doesnt work (no effect), but does on windows

### ISSUE THREAD

**Issue by e01c-dat10** [rockowitz/ddcutil#54]
it did work fine on old monitor(samsung)
but then switched to a newer ASUS and AOC monitor, it didnt work.

does when on windows http://clickmonitorddc.bplaced.net/
also to note, the brightness contrast range##'s are different on the various monitors
(some do contrast overshoot & @ different levels thus different nominal(no curve disrupt) brightness-contrast values)
also suspect different in-between steps for those values, also RGB balance##'s

**Comment by rockowitz** [comment]
There's not much I can make of such a vague report.   Yes, some monitors 
more tightly follow the I2C spec than others.  Yes, some video drivers 
are more tolerant than others of marginal monitors.  Yes, Windows 
drivers may be better in this regard, or it may be that monitor 
manufacturers just test on Windows, not Linux. And yes, different 
monitors have different maximum values for brightness, contrast, etc.  
That's in the DDC spec.

If you'd like for me to say anything more specific, please execute the 
"ddcutil interrogate" command for each monitor and  submit the output as 
attachments.

Sanford
