### ISSUE TITLE
setvcp settings reverts to initial state after few seconds (Dell U2414H)

### ISSUE THREAD

**Issue by prymaszewski** [rockowitz/ddcutil#77]
Hi,

I have a problem with switching inputs of Dell U2414H monitors. I have two of them in my setup, both of them are connected to CentOS 7 machine with DisplayPort and one of them  also to Windows 10 machine with HDMI. When I try to switch from CentOS to Windows with this command:
`setvcp 60 12 --display 2` the screen goes black for a second, than displays "entering power saving mode" and after another 2-3 seconds goes back to displaying CentOS. Switching from Windows to CentOS with [clickmonitorddc](https://clickmonitorddc.bplaced.net/) works fine. Other commands executed on CentOS with ddcutil (e.g. change brightness, contrast) work fine.

Any help would be appriciated. I'm attaching outputs of `ddcutil interrogate` and `ddcutil detect`, if some more info is needed please let me know.

[ddcutil_detect.txt](https://github.com/rockowitz/ddcutil/files/2752127/ddcutil_detect.txt)
[ddcutil_interrogate.txt](https://github.com/rockowitz/ddcutil/files/2752128/ddcutil_interrogate.txt)

**Comment by aryoda** [comment]
Just a guess...

VCP code `60h` (input select) uses the values `0Fh` (hex) for *DisplayPort1* and `10h` for *DisplayPort 2* and the value you are using to switch to Windows (HDMI) is `12h` (= *HDMI2* sic!).

You could try to use the value `11`h instead to switch to *HDMI1*:

`ddcutil setvcp 60 11 --display2`

**Comment by prymaszewski** [comment]
Thank you for a reply, but I'm indeed trying to switch to HDMI-2 port, sorry for the confusion. According to output of `ddcutil capabilities --display 2 --verbose` (attached) value `12` should be acceptable. In any case, connecting the cable to HDMI-1 port and running the command you suggested yields the same result.

[ddcutil_capabilities.txt](https://github.com/rockowitz/ddcutil/files/2752691/ddcutil_capabilities.txt)

I'm also attaching output of `ddcutil setvcp 60 12 --display 2  --verbose --noverify` in case this helps. The `--noverify` option was suggested in some old issue, but the end result is the same.
[ddcutil_setvcp.txt](https://github.com/rockowitz/ddcutil/files/2752693/ddcutil_setvcp.txt)

**Comment by rockowitz** [comment]
To reiterate, you need to specify the command as:
    ddcutil setvcp 60 x12
Not:
    ddcutil setvcp 60 12

**Comment by prymaszewski** [comment]
Yes, you're right, I didn't notice the missing hex prefix.

Thank you for the help, I'll close this issue now.
