### ISSUE TITLE
laptop panels controlling

### ISSUE THREAD

**Issue by bam80** [rockowitz/ddcutil#87]
> ddcutil does not support laptop displays, which are controlled using a special API, not I2C. 

Hello.
Sanford, could you please shed some lite on how the laptop panels are controlled in case of LVDS and eDP?

I'm interested because I decided to upgrade my Lenovo G710 to IPS panel.
For that, I would need LVDS-to-eDP converter.
People saying there could be a chance of loosing brightness regulation capability.

So I'm wondering if there is a fundamental issue here or just those converters are bad designed?

Sorry for offtopic but I haven't found clear information on this.

**Comment by rockowitz** [comment]
Laptop displays are (generally) controlled using ACPI.

As to LVDS-eDP converters, I'm afraid I have nothing to tell you. It's 
at a hardware level that's irrelevant to ddcutil.

Sanford
