### ISSUE TITLE
No version info in shared library name

### ISSUE THREAD

**Issue by hansfn** [rockowitz/ddcutil#90]
When you build ddcutil, libtool reports "libtool version 0:0:0" and /usr/lib/libddcutil.so.0.0.0 is created. This might be on purpose, but if not the build should be modified.

**Comment by rockowitz** [comment]
Until recently the API was changing rapidly, so SONAME versioning was 
not turned on.  Starting with the next release of ddcutil (in final 
packaging, see github branch 0.9.6). SONAME versioning is implemented, 
and the new libddcutil version will be 1.0.0.

Sanford
